version: "3"

services:

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"

    environment:

      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword


  web-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./pizza-api/pizza_api/.env
    volumes:
      - .:/pizza-delivery-api
    depends_on:
      -  postgres
